# Generated by Django 3.1.2 on 2020-10-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_id', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
